language: node_js
node_js:
  - '13'
cache:
  yarn: true
  directories:
    - dist
    - .cache
script:
  - yarn build # Generate static HTML files

deploy:
  # Use Github pages deploy process
  provider: pages
  # Keep built pages
  skip-cleanup: true
  # Directory where your generated files are located
  local_dir: dist
  # Github security/auth token
  github-token: $GITHUB_TOKEN
  # Incremental commit to keep old build/files from previous deployments
  keep-history: true
  # Git repo to push to
  repo: ngx-semantic/ngx-semantic-docs
  # Git branch on which it should deploy (master, gh-pages, foo...)
  target_branch: master
  on:
    # Which branch on commit/push will trigger deployment
    branch: master
