language: node_js
node_js:
  - '13'
cache:
  yarn: true
  directories:
    - dist
    - .cache
script:
  - yarn build # Generate static HTML files
  - cp dist/index.html dist/404.html

deploy:
  # Use Github pages deploy process
  provider: pages
  # Keep built pages
  skip-cleanup: true
  # Directory where generated files are located
  local_dir: dist
  # Github security/auth token
  github-token: $GITHUB_TOKEN
  # Rewrite history on each deploy so that we dont accumulate built js files
  keep-history: false
  # Git repo to push to
  repo: ngx-semantic/ngx-semantic.github.io
  # Git branch on which it should deploy
  target_branch: master
  on:
    # Which branch on commit/push will trigger deployment
    branch: master
