version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:19.7.0
    steps:
      - checkout
      - run: |
          node --version
          yarn --version
          npm install -g @angular/cli
          yarn install
          yarn build
          cp dist/index.html dist/404.html
          
          cd dist
          git init
          git config credential.helper 'cache --timeout=120'
          git config user.email "indexz3ro@aol.com"
          git config user.name "CI deploy bot"
          git add .
          git commit -m "Deploy updated docs via CircleCI"
          # Push quietly to prevent showing the token in log
          git push -f -q https://${CI_GITHUB_TOKEN}@github.com/ngx-semantic/ngx-semantic.github.io.git master
