version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:22.0.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run build
          command: yarn build
  deploy:
    docker:
      - image: cimg/node:20.9.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run: |
          yarn build
          cp dist/index.html dist/404.html
      - run: |
          git config --global user.email "indexz3ro@aol.com"
          git config --global user.name "CircleCI"

          git clone https://bolorundurowb:${CI_GITHUB_TOKEN}@github.com/ngx-semantic/ngx-semantic.github.io.git
          cd ngx-semantic.github.io
          git checkout master          

          rm -r *
          cp -r ~/project/dist/* .

          git add .
          git commit -m "Auto-deployed from CircleCI"
          git push origin master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - deploy:
          filters:
            branches:
              only: master
