version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:19.7.0
    steps:
      - checkout
      - run: |
          node --version
          yarn --version
          npm install -g @angular/cli
          yarn install
          yarn build
          cp dist/index.html dist/404.html
